global:
  identity:
    auth:
      # Disable the Identity authentication for local development
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false

# Disable identity as part of the Camunda core
identity:
  enabled: false

# Disable keycloak
identityKeycloak:
  enabled: false

optimize:
  enabled: false

# Reduce for Zeebe and Gateway the configured replicas and with that the required resources
# to get it running locally
zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 10Gi

zeebeGateway:
  replicas: 1

connectors:
  enabled: true
  inbound:
    mode: disabled
  resources:
    limits:
      cpu: 500m
      memory: 800Mi
    requests:
      cpu: 300m
      memory: 500Mi

elasticsearch:
  master:
    replicaCount: 1
    # Request smaller persistent volumes.
    persistence:
      size: 15Gi
    resources:
      limits:
        cpu: 800m
        memory: 1500Mi
      requests:
        cpu: 400m
        memory: 1000Mi

tasklist:
  resources:
    limits:
      cpu: 500m
      memory: 600Mi
    requests:
      cpu: 300m
      memory: 500Mi

operate:
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 200m
      memory: 400Mi