apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gpon.name" . }}
  labels:
    {{- include "gpon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gpon.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gpon.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: APP_BASE_URL
              value: {{ .Values.config.baseUrl }}
            - name: FLOW_BROKER_HOST
              value: {{ .Values.config.flowBrokerHost }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: management
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}